### ISSUE TITLE
Search Bar component props doesn't work

### ISSUE THREAD

**Issue by GustavoACupula** [vtex-apps/store-components#226]
**Describe the bug**
The props `placeholder` and `emptyPlaceholder`  does not work when sending a string, It uses the formatted message configured in the locales folder

**To Reproduce**

**Expected behavior**
The rendered text will be the props placeholder

**Screenshots**
![image](https://user-images.githubusercontent.com/40472245/49581599-9a2ea380-f939-11e8-91fe-f1cb0069f9e7.png)
![image](https://user-images.githubusercontent.com/40472245/49581619-b0d4fa80-f939-11e8-8192-a67153da6c61.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 70

**Smartphone (please complete the following information):**

**Additional context**

**Comment by caljp13** [comment]
I have the same problem with the props `placeholder`, `emptyPlaceholder`, `compactMode` and `iconClasses`.

But I'm using `blocks.json`, is there some way to get around this problem?

**Comment by hapoza** [comment]
@caljp13 Translate the messages that @luciannojunior mentioned using messages builder

**Comment by hapoza** [comment]
Actually, the message ids changed, I found 'store/search.placeholder' and "store/search.searchFor"
