### ISSUE TITLE
Configuration to change product thumbnails - ProductImages

### ISSUE THREAD

**Issue by gustavo-vasconcellos** [vtex-apps/store-components#359]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Add a configuration into `ProductImages` to define where the thumbnails will be displayed, can be `left`, `right` or `below` the selected product image.

**Describe alternatives you've considered**
This can be resolved if you add a props to receive the strings `left`, `right` or `below` and make a component to render one of them, like the app `product-summary` render the "normal" and "inline" components.

**Additional context**
-

**Comment by rerissondaniel** [comment]
Hi! Thanks for opening this issue. This is a very important option to have, I'm adding it to our backlog and will return as soon as possible.

**Comment by rerissondaniel** [comment]
@gustavo-vasconcellos Does it solve your problem? I noticed the implementation missed the `below` option, but we're working on that.

**Comment by gustavo-vasconcellos** [comment]
@rerissondaniel Yes, adding the `below` option it will solve the problem ;)
