### ISSUE TITLE
 Add other optionals social networks to share a product page.

### ISSUE THREAD

**Issue by Gatamura** [vtex-apps/store-components#369]
**Is your feature request related to a problem? Please describe.**
We expect a boolean props to show other social networks.

**Describe the solution you'd like**
Add other networks on share.

ex:

Pinterest: http://pinterest.com/pin/create/button/?url={{ImagemURL}}.jpg.
E-mail: mailto:?subject={{subject}};body={{body}}.

**Comment by rerissondaniel** [comment]
Hi @Gatamura! Thanks for opening this issue. Currently you can add the email option by setting it in storefront or passing  {Email: true} in the _social_ prop (like we are doing with whatsapp, telegram and others). We will add the Pinterest option as soon as possible. Is there any other social network you would want us to include?

**Comment by Gatamura** [comment]
Hello @rerissondaniel thanks for the reply! Apparently we need to send {E-mail: true}, only "Email" causes an error.
At first only the Pinterest already would help us enough.
Thank you!
