### ISSUE TITLE
Add component buy together

### ISSUE THREAD

**Issue by Gatamura** [vtex-apps/store-components#373]
**Is your feature request related to a problem? Please describe.**
We would like to know if this component is in the backlog, as it is common in many stores.

**Comment by rerissondaniel** [comment]
Hi @Gatamura,

We have the [product-kit](https://github.com/vtex-apps/product-kit) app. Please let us know if it attends your needs.

**Comment by Gatamura** [comment]
Hello @rerissondaniel,

From what I understand the product kit renders a Slider of products contained within a "look" in the CMS. A point of view is a component where the customer can buy the product with an additional product recommendation. 
The Vtex portal itself has a control that does this vtex.cmc: BuyTogether.
