### ISSUE TITLE
Add More Configuration Options to CategoryHighlights Component

### ISSUE THREAD

**Issue by sahanljc** [vtex-apps/store-components#379]
**Is your feature request related to a problem? Please describe.**
We plan to use the `CategoriesHighlights` component to render a category gallery in the homepage. We need to

- pass a link to the category card
- show the name of each category
- increase the number of items per row
- show a section title and a line separator for the highlighted section
- add an optional display mode to support a shelf

**Describe the solution you'd like**
The `CategoryCard` will accept a page/params pair as well as a direct link which in turn will be passed to the `Link` component to build the href. The card will have a heading (`<h3>`). There will be a title above the main `<div>` and a line separator below.
The component will accept 6 and 8 for `quantityOfItems` so that we can show 6 or 8 items per row.
Based on the configuration of the display mode, we additionally provide support for a shelf-like view, resulting in a new component.

**Comment by klzns** [comment]
You mean something like this, right?

![image](https://user-images.githubusercontent.com/284515/55002738-e15aa600-4fb5-11e9-9b9c-6f0cfa646656.png)

**Comment by sahanljc** [comment]
Yes, but in addition we need to have a name for each category, a title and a line separator for the section, as in the screenshot attached below.
![image1](https://user-images.githubusercontent.com/42151054/55054000-3533c080-5084-11e9-9adc-1cac7155b425.png)
