### ISSUE TITLE
SKU Selector - More than two specifications

### ISSUE THREAD

**Issue by perillosantana** [vtex-apps/store-components#393]
**Is your feature request related to a problem? Please describe.**
The SKU Selector does not render more than two items of the specifications.

**Describe the solution you'd like**
That the SKU Selector could render all specifications and heard a way to identify the sku on the front (a class based on the sku name)

**Describe alternatives you've considered**
Develop a proper component to handle SKU selection

**Additional context**
https://github.com/vtex-apps/store-components/blob/279de2e49b1f2008d99615ca93da774c2d96d55c/react/components/SKUSelector/README.md
https://drive.google.com/open?id=1JoXUWdMhXmL66DuKC_Ii6koxnVLn8Gn2

**Comment by hapoza** [comment]
@perillosantana I might have misunderstood what you mean, but I'm pretty sure that if the product has more than one specification, it renders all of them, it can be seen working here https://storetheme.vtex.com/classic-shoes/p
