### ISSUE TITLE
We need to show 2 products at a time on mobile mode

### ISSUE THREAD

**Issue by kyoruu** [vtex-apps/store-components#546]
**Is your feature request related to a problem? Please describe.**
The shelf is just showing one product.

**Describe the solution you'd like**
A option to show at least 2 itens per slide, on mobile mode.

**Describe alternatives you've considered**
Tried to achieve with CSS, but it just glitch all the slick.

**Additional context**
What we got now: https://prnt.sc/oqnr0p
What we need: https://prnt.sc/oqns19

**Comment by klzns** [comment]
Hi, that's your lucky day. We just launched this feature! 

You can read more here: https://github.com/vtex-apps/release-notes/blob/master/docs/2019-week-31/minimum-items-shelf.md

(Full release notes of this week: https://github.com/vtex-apps/release-notes/tree/master/docs/2019-week-31)
