### ISSUE TITLE
Product-description button doesn't work outside the product-details element

### ISSUE THREAD

**Issue by GabrielBarross** [vtex-apps/store-components#619]
**Describe the bug**
The product-description button was working without the necessity of the main component being a "product-details"children. Now there is no action when the button is clicked.
Example:
https://niazi.myvtex.com/tapete-galant-2-00-x-2-50---sao-carlos/p

**To Reproduce**
1. Set a component "product-description" anywhere inside the product page.
2. Go to the product page.
3. Try to click in the "Ver Mais" button.

**Expected behavior**
When the button is clicked, the box should show the entire description of the product.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/53904010/67702387-6f559f80-f990-11e9-85f0-84369bd762a2.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [Chrome 77 on Windows 10]

**Smartphone (please complete the following information):**
 - Device: [Samsung J7]
 - OS: [Android]
 - Browser [Chrome]
 - Version [Chrome 78 on Android 8.1]

**Comment by Klynger** [comment]
Sorry about the delay @GabrielBarross , but was this problem solved?

**Comment by Klynger** [comment]
It seems to be solved already
