### ISSUE TITLE
product-brand props not applied

### ISSUE THREAD

**Issue by cristian-milea** [vtex-apps/store-components#715]
**Describe the bug**
"vtex.store-components:product-brand" doesn't apply props. Logo is still used instead of text

**To Reproduce**
`
"flex-layout.col#pri-left": {
    "children": [
      "vtex.store-components:product-brand"
    ],
  },
  "vtex.store-components:product-brand": { 
    "props": {
      "displayMode": "text"
    }
  }
`

**Screenshots**
<img width="1680" alt="Screenshot 2020-02-23 at 15 39 56" src="https://user-images.githubusercontent.com/4988454/75117736-d3f1e400-567c-11ea-95ee-f83d227ed979.png">

**Comment by Klynger** [comment]
Hey cristian, is this still happening?

**Comment by Klynger** [comment]
Hey @cristian-milea is this still happening?

**Comment by victorhmp** [comment]
Closing this due to a lack of response.
@cristian-milea if this is still happening, please open a new Issue over at https://github.com/vtex-apps/store-discussions.

**Comment by doruradu** [comment]
> Hey @cristian-milea is this still happening?

Yes, it's still a bug :(

**Comment by cristian-milea** [comment]
@Klynger , sorry for the late response, I was unavailable for a few months.
yes, it is still happening
```  "name": "store-theme",
  "version": "0.0.3",
  "builders": {
    "assets": "0.x",
    "styles": "2.x",
    "store": "0.x",
    "sitemap": "0.x",
    "docs": "0.x"
  },```

```
"vtex.store-components": "3.x",
```

**Comment by klzns** [comment]
Referencing the workaround while we work on the fix:
https://github.com/vtex-apps/store-discussion/issues/372#issuecomment-672226546
