### ISSUE TITLE
Product Images - First Image on Desktop won't zoom out.

### ISSUE THREAD

**Issue by jpgutti** [vtex-apps/store-components#738]
**Describe the bug**
On Desktop only, after zoom in the first product image, it won't zoom out, until the user clicks on other images, then it works properly.

**To Reproduce**
1. Go to www.bennemann.com.br
2. Click on any product
3. Zoom in the image with one click, and try to zoom out with another click.

**Expected behavior**
Expected the zoom to work properly, zooming in and zooming out.

**Comment by Klynger** [comment]
Hi @jpgutti , I tried to reproduce the error and it didn't happen, could you check if it is still happening and share some more information?

I'm using the Google Chrome 81.0.4044.92

**Comment by jpgutti** [comment]
@Klynger It's still happening...

Only in the first image that bug is observed.
When zoomed in, you can't zoomed out.

**Comment by Klynger** [comment]
Which browser are you using?

**Comment by jpgutti** [comment]
Chrome in the exactly same version.

**Comment by Klynger** [comment]
@jpgutti what is the account of this store?

**Comment by jpgutti** [comment]
@Klynger bennemann

**Comment by Klynger** [comment]
This PR should fix this, thank you for the issue @jpgutti
