### ISSUE TITLE
Buy button - Enable run functions 

### ISSUE THREAD

**Issue by felipe-ssilva** [vtex-apps/store-components#773]
**Is your feature request related to a problem? Please describe.**
We have some difficulties in tracking native VTEX IO components. Example: collect clicks on the buy button.

**Describe the solution you'd like**
Enable execution of functions.
**Example**: onClick={() => this.buyButtonTracking(skuItems[0].skuId, productName, commertialOffer.Price, '1')}

**Additional context**
![image](https://user-images.githubusercontent.com/4562886/82693381-d3df9100-9c37-11ea-85d7-1e5f766fd294.png)

**Comment by klzns** [comment]
What the `buyButtonTracking` function does in practice?

**Comment by felipe-ssilva** [comment]
@klzns sending data to google analytics by datalayer. ID, name, selling price and quantity.

**Comment by klzns** [comment]
We already send those info to the dataLayer by the Google Tag Manager app. 
https://github.com/vtex-apps/google-tag-manager

Are you reimplementing this app?
