### ISSUE TITLE
Image link prop not working

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-components#782]
**Describe the bug**
Trying to add la link to an image but the "href" attribute is not rendered in the frontend.

**To Reproduce**
1. Add an image using the image block
`"image#img-vegan": {
        "props":{
          "src": "assets/imagini/icon-vegan.svg",
          "link":"/diete-speciale/vegan"
        }
      }
`
2. Link the app

**Expected behavior**
The image should redirect the user to the specified link, but the <a> tag wrapping the img has a blank href.

**Screenshots**
![image](https://user-images.githubusercontent.com/42587916/83645320-033cb900-a5bb-11ea-8154-dfc65ac4f879.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 3.x

**Additional context**
You can see the live bug here: beta--sanovita.myvtex.com

**Comment by Klynger** [comment]
Hi @doruradu, the prop `link` is not a string, you can check the values here https://github.com/vtex-apps/store-image/tree/master/docs

**Comment by klzns** [comment]
Just complementing

![image](https://user-images.githubusercontent.com/284515/83648141-14ba9c80-a58c-11ea-8a81-6db1bce55743.png)

**Comment by doruradu** [comment]
#omg, didn't see that in the documentation (https://vtex.io/docs/components/all/vtex.store-components@3.116.0/image/). Thanks x 23482974239!!
