### ISSUE TITLE
Lack of class in the validation of the input.

### ISSUE THREAD

**Issue by perillosantana** [vtex-apps/store-components#871]
**Is your feature request related to a problem? Please describe.**
There is no class to handle the error resulting from input validation.

![alt text](https://i.ibb.co/Hrd9MXy/Tela-inteira-07-10-2020-18-08.png)

**Describe the solution you'd like**
Add a class to handle that message.

**Comment by klzns** [comment]
Fix on the way: https://github.com/vtex/styleguide/pull/1340
