### ISSUE TITLE
Field - Quantity

### ISSUE THREAD

**Issue by felipe-ssilva** [vtex-apps/store-components#874]
**Is your feature request related to a problem? Please describe.**
I need to display the quantity field like is show in the image:
![image](https://user-images.githubusercontent.com/4562886/96497528-322d9180-1221-11eb-9478-f6b4a1d71ee5.png)

**Describe the solution you'd like**
Change prop in BuyButton component, also like:

`
<BuyButton
     quantityToBeAdded={quantityToBeAdded}
     available={isAvailable}
     skuItems={skuItems}
     isOneClickBuy={isOneClickBuy}
     shouldOpenMinicart= {shouldOpenMinicart}
/>
`

**Comment by klzns** [comment]
Hi, @felipe-ssilva,

I think you can achieve this using the blocks: [`product-quantity`](https://vtex.io/docs/components/all/vtex.product-quantity/) and [`add-to-cart-button`](https://vtex.io/docs/components/all/vtex.add-to-cart-button/)

Have you tried this?

**Comment by felipe-ssilva** [comment]
Hi @klzns, tks for answer.

I using this:
```javascript
import BuyButton from 'vtex.store-components/BuyButton'
```

```javascript
<BuyButton
  available={isAvailable}
  skuItems={skuItems}
  isOneClickBuy={isOneClickBuy}
  shouldOpenMinicart= {shouldOpenMinicart}
/>
```
For using [`product-quantity`](https://vtex.io/docs/components/all/vtex.product-quantity/), i needed refactor all current product page structure 😩
