### ISSUE TITLE
[Urgent] Availability Subcriber returns 403

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/store-components#925]
**Describe the bug**
The availabilitySubscriber application no longer works. When completing the form returns error 403. There were no problems until recently.

The problem it's on several sites
![error](https://user-images.githubusercontent.com/43498488/109957599-d6eece00-7ced-11eb-9357-49152d5106e8.jpg)

**To Reproduce**
1. Go to https://customsoft.myvtex.com/curea-negru-barbati-35722/p
2. Fill out the availability subscriber form

**Comment by klzns** [comment]
There's no entity AS in the MasterData of this store. You should create one with public write permission with the fields instructed here:

https://github.com/vtex-apps/store-components/blob/master/docs/AvailabilitySubscriber.md#usage

**Comment by khrizzcristian** [comment]
Ty. on another store i have AS entity but the fields doesn't have public write permission.

**Comment by khrizzcristian** [comment]
It works. Thanks :)
